using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using UnityEngine;

public class StringUtils
{
    public static string projectName => "Factory Factory";

    public static void StrictModerationCheckThrowsError(string input)
    {
        input = Regex.Replace(input, @"[\W\d]", "");

        BannedPhraseCheckThrowsError(input);
    }

    public static void BannedPhraseCheckThrowsError(string text)
    {
        text = Regex.Replace(text, @"[^\w\s]", "");

        foreach (string word in bannedPhrases)
        {
            Regex rx = new Regex($@"\b({word})[(ism)(y)(ry)(s)(ed)(ing)(er)]*\b", RegexOptions.IgnoreCase);
            if (rx.IsMatch(text))
            {
                throw new ModerationBannedWordException($"Text contained banned word \"{word}\"");
            }
        }
    }

    public static string ReplaceAllBannedPhrases(string text)
    {
        foreach (string word in bannedPhrases)
        {
            Regex rx = new Regex($@"\b({word})[(ism)(y)(ry)(s)(ed)(ing)(er)]*\b", RegexOptions.IgnoreCase);

            text = rx.Replace(text, goodWords[UnityEngine.Random.Range(0, goodWords.Count)]);
        }

        return text;
    }

    public static string StrictSanitizeText(string input, bool allowNumbers)
    {
        // Remove all spaces, characters, and numbers
        // IE: "g.a2m!e.r" -> "gamer"
        string regex = allowNumbers ? @"[\W]" : @"[\W\d]";
        return Regex.Replace(input, regex, "");
    }

    public static string Sanitize(string input)
    {
        var sanitized = Regex.Replace(input, "%", " percent");  // Get the bot to pronounce "percent"
        sanitized = Regex.Replace(sanitized, "\"", "");         // Special case to remove quotation marks
        sanitized = Regex.Replace(sanitized, @"(\.(com|org|edu|net|cr|gov|sh|ru|cn|mx))", "");
        return Regex.Replace(sanitized, @"[^a-zA-Z0-9- .,!?'\n]", "");  // Only allow these symbols
    }


    /// <summary>
    /// Replace "{keyword}" in a string. Used to insert text into prompts.
    /// If the keyword is "{product name}" do not include the curly brackets in toReplace
    /// </summary>
    /// <param name="replaceWith"></param>
    /// <param name="text"></param>
    /// <returns></returns>
    public static string ReplaceTextInString(string toReplace, string replaceWith, string text)
    {
        string tempStringToReplace = "{" + toReplace + "}";
        if (string.IsNullOrEmpty(replaceWith))
            return text;

        string part1;
        string part2;

        while (text.Contains(tempStringToReplace))
        {
            part1 = text.Substring(0, text.IndexOf(tempStringToReplace));
            part2 = text.Substring(text.IndexOf(tempStringToReplace) + tempStringToReplace.Length);

            text = part1 + replaceWith + part2;
        }

        return text;
    }

    /// <summary>
    /// Remove "Step 1. ", "1. ", "Narrator: ", and "Next, " from a string.
    /// </summary>
    /// <param name="text"></param>
    /// <returns></returns>
    public static string RemoveStepIntros(string text)
    {
        text = Regex.Replace(text, @"([sS]tep \d+\.\s)", ""); // Step 1.
        text = Regex.Replace(text, @"(\d+\.\s)", "");         // 1. 
        text = Regex.Replace(text, @"(Narrator: )", "");
        text = Regex.Replace(text, @"(Next, )", "");
        return text;
    }

    /// <summary>
    /// Replace all \\ with \n
    /// </summary>
    /// <param name="text"></param>
    /// <returns></returns>
    public static string FixNewlines(string text)
    {
        return Regex.Replace(text, "(\\\\\\\\)", "\n");
    }

    /// <summary>
    /// Final script sanitization
    /// </summary>
    /// <param name="text"></param>
    /// <returns></returns>
    public static string FinalScriptCleanup(string text)
    {
        text = Sanitize(text);
        return text;
    }

    public static IEnumerable<string> SplitToLines(string input)
    {
        if (input == null)
        {
            yield break;
        }

        using (System.IO.StringReader reader = new System.IO.StringReader(input))
        {
            string line;
            while ((line = reader.ReadLine()) != null)
            {
                yield return line;
            }
        }
    }

    public static List<string> goodWords = new List<string>
    {
        "unicorn",
        "rainbow",
        "laptop",
        "car tire"
    };

    public static List<string> locations = new List<string>
    {
        "office",
        "home",
        "factory",
        "jobsite",
        "spacestation",
        "tent",
        "summer camp",
        "sporting event",
        "airplane",
        "school",
        "garage",
        "store",
        "grocery store",
        "asian grocery",
        "sporting goods store",
        "bank",
        "toystore",
        "workshop",
        "resturaunt",
        "university",
        "music venue",
        "record store",
        "music shop",
        "dump",
        "gym",
        "fast food resturaunt"
    };

    public static List<string> productPromptOptions = new List<string>
    {
        "cold blowtorch",
        "self-driving couch",
        "toaster",
        "singing novelty fish",
        "tiny folding bike",
        "gummy cellphone",
        "artificial banana peel",
        "mechanical spaghetti fork",
        "self-stirring pot",
        "light-up elephant shoes",
        "automatic pancake machine",
        "ai chatbot",
        "weather machine",
        "maple syrup machine",
        "virtual youtuber",
        "fake leather shoes",
        "burnt toast",
        "monster trucks",
        "artifical fish",
        "lofi hip-hop beats",
        "virtual idols",
        "pizza cutting machine",
        "human-sized hampster ball",
        "horseshoes",
        "rubber ducks",
        "basketballs",
        "birthday cakes",
        "broken cellphones",
        "giant tables",
        "soup crates",
        "stacks",
        "cooks",
        "androids",
        "magic chopsticks"
    };

	public static List<string> bannedPhrases = new List<string>
    {
        "Agoraphobia",
        "Schizophrenia",
        "antisocial",
        "dysphoria",
        "Anorexia",
        "sadism",
        "Post-traumatic",
        "PTSD",
        "bipolar",
        "mental illness",

        "hooker",
        "prostitute",
        "femboy",
        "plus-size",
        "gay",
        "lesbian",
        "penis",
        "arsonists",
        "bullshit",
        "sensual",
        "harem",
        "maiden",
        "wife",
        "concubine",
        "mistress",
        "lover",
        "girlfriend",
        "courtesan",
        "lady",
        "madam",
        "gal",
        "damsel",
        "senora",
        "lass",
        "dame",
        "belle",
        "mum",
        "matron",
        "mspouse",
        "bride",
        "homemaker",
        "stay-at-home",
        "girl",
        "woman",
        "women",
        "female",
        "chamber",
        "baby",
        "babies",
        "young",
        "servant",
        "bondman",
        "chattel",
        "indentured",
        "serf",
        "bondsman",
        "helot",
        "bondswoman",
        "domestic",
        "servant",
        "menial",
        "handmaid",
        "handmaiden",
        "lackey",
        "odalisque",
        "indentured ",
        "drudge",
        "slaver",
        "beer",
        "wine",
        "alcohol",
        "alcoholic",
        "booze",
        "liquer",
        "4loko",
        "coors",
        "coolers",
        "winery",
        "pbr",
        "brewery",
        "distillery",
        "distill",
        "miller",
        "spirits",
        "brandy",
        "whiskey",
        "mescal",
        "brewski",
        "barley",
        "shot",
        "malt",
        "brewage",
        "grog",
        "inhebriated",
        "cocktail",
        "sake",
        "gin",
        "apertif",
        "nightcap",
        "noose",
        "knot",
        "taquila",
        "vodka",
        "rum",
        "cognac",
        "brandy",
        "mixer",
        "moonshine",
        "prison",
        "jail",
        "cage",
        "kennel",
        "trap",
        "caffeine",
        "caffinated",
        "covid",
        "covid-19",
        "corona",
        "virus",
        "coronavirus",
        "vaccine",
        "mate",
        "priest",
        "rabbi",
        "altar",
        "spliff",
        "splif",
        "joint",
        "high ball",
        "highball",
        "chewie",
        "dutch courage",
        "liquid courage",
        "doujin",
        "trump",
        "obama",
        "biden",
        "abv",
        "bong",
        "drug",
        "medicine",
        "urine",
        "poop",
        "pee",
        "peepee",
        "poo",
        "poopoo",
        "dookie",
        "dung",
        "feces",
        "excrement",
        "excretion",
        "stool",
        "droppings",
        "communism",
        "communist",
        "imperialist",
        "cigarette",
        "cigar",
        "nicotine",
        "vape",
        "smoking",
        "buttocks",
        "rump",
        "fanny",
        "backside",
        "heinie",
        "hiny",
        "booty",
        "bootie",
        "posterior",
        "islander",
        "inflation",
        "victim",
        "prey",
        "whipping",
        "dumpy",
        "thic",
        "thighs",
        "thigh",
        "pubis",
        "pubis mons",
        "pubic",
        "pubic bone",
        "foreskin",
        "frenulum",
        "glans",
        "glands",
        "dissected",
        "dissection",
        "dissect",
        "turgid",
        "swollen",
        "erect",
        "erectile",
        "beanis",
        "pillow biter",
        "toes",
        "dirty heisman",
        "missionary",
        "arse",
        "gooch",
        "government cheese",
        "sucking",
        "margarita toe",
        "barbie",
        "cabbage patch",
        "anatomy",
        "anatomically",
        "lesbomancy",
        "underaged",
        "kiss",
        "smooch",
        "smoocher",
        "kissing",
        "kisser",
        "creampie",
        "cream pie",
        "basterd",
        "shotacon",
        "lolicon",
        "ephebophile",
        "ephebo",
        "the red wave",
        "fertilize",
        "engrish",
        "gonad",
        "gonads",
        "testes",
        "horn dog",
        "virgin",
        "bang",
        "go down on",
        "copulate",
        "blue waffle",
        "poro",
        "double dutch rotor",
        "cloaca",
        "upper decker",
        "wank",
        "piss",
        "saddlebacking",
        "saddleback",
        "duck butter",
        "cleansing",
        "necro",
        "munting",
        "blumpkin",
        "cameltoe",
        "camel toe",
        "hot karl",
        "climax",
        "serbian film",
        "boku no pico",

        "Tourette",
        "HIV",
        "sedative",
        "sedate",
        "Amphetamine",
        "self harm",
        "self-harm",
        "selfharm",
        "intoxication",
        "opioid",
        "Heroin",
        "Marijuana",
        "LSD",
        "MDMA",
        "Ecstasy",
        "PCP",
        "Psilocybin",
        "Fentanyl",
        "Cocaine",
        "Methamphetamine",
        "Oxycodone",
        "Hydrocodone",
        "Hydromorphone",
        "Ritalin",
        "Adderall",
        "Vyvanse",
        "Concerta",
        "Valium",
        "Xanax",
        "Ketamine",
        "Marijuana",
        "Barbiturate",
        "Benzodiazepine",
        "gamma-hydroxybutyrate",
        "Rohypnol",
        "Quaaludes",
        "methaqualone",
        "Phenobarbital",
        "Nembutal",
        "pentobarbital",
        "Valium",
        "diazepam",
        "Xanax",
        "alprazolam",
        "Ativan",
        "lorazepam",
        "Klonopin",
        "clonazepam",
        "Lunesta",
        "eszopiclone",
        "Ambien",
        "zolpidem",
        "Sonata",
        "zaleplon",
        "Benzos",
        "Phennies",
        "Molly",
        "Ketamine",
        "Mescaline",
        "peyote",
        "Blotter",
        "Special K",
        "Angel dust",
        "Whippets",
        "Huff",
        "painkiller",
        "Codeine",
        "Sublimaze",
        "Actiq",
        "Duragesic",
        "Vicodin",
        "Zohydro",
        "Lortab",
        "Norco",
        "Exalgo",
        "Meperidine",
        "Demerol",
        "Methadone",
        "Methadose",
        "Dolophine",
        "Morphine",
        "Duramorph",
        "Contin",
        "Oxycodone",
        "OxyContin",
        "Percocet",
        "Percodan",
        "Oxymorphone",
        "Opana",
        "Black tar",
        "Boldenone",
        "Nandrolone",
        "Methandienone",
        "testosterone",
        "Roids",
        "Meth",

        "loli",
        "shota",
        "oppai",
        "paizuri",
        "torture",
        "ffm",
        "threesome",
        "bondage",
        "nakadashi",
        "censorship",
        "matingpress",
        "bbm",
        "gokkun",
        "exhibition",
        "voyeur",
        "bukkake",
        "snuff",
        "shimapan",
        "defloration",
        "inseki",
        "futa",
        "cumflation",
        "cervix",
        "ahegao",
        "impregnation",
        "skinsuit",
        "tentacle",
        "yaoi",
        "penetration",
        "femdom",
        "crossdressing",
        "garter",
        "gag",
        "enema",
        "crotch",
        "tribadism",
        "smegma",
        "chloroform",
        "chastity",
        "milking",
        "pasties",
        "armpit",
        "diaper",
        "vomit",
        "phimosis",
        "selfcest",
        "shimaidon",
        "mesuiki",
        "omorashi",
        "stimulation",
        "scrotal",
        "Testes",
        "Vas deferens",
        "Prostate",
        "Seminal vesicles",
        "Epididymis",
        "Urethra",
        "Ovaries",
        "Fallopian",
        "Uterus",
        "Vagina",
        "Clitoris",
        "Labia",
        "Vulva",
        "Cervix",

        "heroin",
        "marijuana",
        "lsd",
        "mdma",
        "ecstasy",
        "pcp",
        "psilocybin",
        "meth",
        "meth",
        "baby",
        "babies",
        "toddler",
        "infant",
        "newborn",
        "antisemitism",
        "antisemite",
        "scrotum",
        "scrote",
        "onahoae",
        "oppai",
        "ecchi",
        "husband",
        "wife",
        "gaydar",
        "panties",
        "hentai",
        "make love",
        "made love",
        "making love",
        "attack helicopter",
        "attack hellicopter",
        "porn",
        "porno",
        "pornography",
        "pornographic",
        "poop",
        "slime",
        "vomit",
        "the hell",
        "Murder-suicide",
        "Self-immolation",
        "Autocide",
        "Medicide",
        "Avunculicide",
        "Familicide",
        "Filicide",
        "Fratricide",
        "Geronticide",
        "Infanticide",
        "Mariticide",
        "Matricide",
        "Neonaticide",
        "Nepoticide",
        "Parricide",
        "parenticide",
        "Patricide",
        "Prolicide",
        "Senicide",
        "Siblicide",
        "Sororicide",
        "Uxoricide",
        "Amicicide",
        "Androcide",
        "Assassination",
        "Capital punishment",
        "Casualty",
        "Collateral damage",
        "Democide",
        "populicide",
        "Eugenics",
        "killing",
        "Euthanasia",
        "Familiaricide",
        "Femicide",
        "gynecide",
        "gynaecide",
        "gynocide",
        "Feticide",
        "Fragging",
        "Gendercide",
        "Genocide",
        "Homicide",
        "sacrifice",
        "Massacre",
        "Murder",
        "Manslaughter",
        "Omnicide",
        "Pedicide",
        "Senicide",
        "gas chamber",
        "matricide",
        "infanticide",
        "homocide",
        "genocide",
        "jews",
        "jew",
        "jewish",
        "jewry",
        "nazi",
        "hitler",
        "white power",
        "whitepower",
        "kkk",
        "euthanize",
        "toilet brush",
        "ethical",
        "electric shock",
        "electrocution",
        "stab",
        "stabbing",
        "attack",
        "assault",
        "anal",
        "analsex",
        "ass",
        "bitch",
        "blowjob",
        "bomb",
        "bombing",
        "bomber",
        "boob",
        "boobjob",
        "buttfuck",
        "buttplug",
        "cameltoe",
        "chink",
        "chinky",
        "clit",
        "cnilingus",
        "cock",
        "cockblock",
        "condom",
        "cum",
        "cumm",
        "cumming",
        "cumshot",
        "cunillingus",
        "cunt",
        "dick",
        "dickhead",
        "dildo",
        "dipshit",
        "dumbass",
        "dyke",
        "ejaculate",
        "ejaculation",
        "facefucker",
        "faggot",
        "fagot",
        "fatass",
        "fellatio",
        "fingerfuck",
        "fistfuck",
        "foreskin",
        "fuck",
        "gangbang",
        "genital",
        "gory",
        "gore",
        "gun",
        "gunpowder",
        "handjob",
        "heroin",
        "herpes",
        "homo",
        "hore",
        "horny",
        "horseshit",
        "jackass",
        "jackoff",
        "jackshit",
        "jap",
        "jerkoff",
        "jew",
        "jigga",
        "jigger",
        "jiz",
        "jizz",
        "juggalo",
        "kike",
        "kill",
        "kissass",
        "kock",
        "koon",
        "kum",
        "kunilingus",
        "lesbo",
        "lethal",
        "lethality",
        "limpdick",
        "lolita",
        "loli",
        "lovejuice",
        "lubejob",
        "lynch",
        "machinegun",
        "mastabate",
        "masterbate",
        "masturbate",
        "masturbating",
        "masturbator",
        "meth",
        "missile",
        "molest",
        "molestation",
        "molester",
        "molestor",
        "mothafuck",
        "mothafucka",
        "mothafucker",
        "muff",
        "murder",
        "nazi",
        "negro",
        "negroes",
        "negroid",
        "nig",
        "niger",
        "nigerian",
        "nigerians",
        "nigg",
        "nigga",
        "niggah",
        "niggard",
        "niggarded",
        "niggarding",
        "niggardliness",
        "niggardly",
        "niggards",
        "niggaz",
        "nigger",
        "niggerhead",
        "niggerhole",
        "niggers",
        "niggle",
        "niggled",
        "niggles",
        "niggling",
        "nigglings",
        "niggor",
        "niggur",
        "niglet",
        "nignog",
        "nigr",
        "nigra",
        "nigre",
        "nuke",
        "nuclearbomb",
        "orgasm",
        "orgies",
        "orgy",
        "pansy",
        "pee-pee",
        "peehole",
        "pedo",
        "pedophile",
        "pedophilia",
        "perv",
        "phonesex",
        "phuk",
        "phuq",
        "piss",
        "pissbaby",
        "pissboy",
        "pissgirl",
        "playboy",
        "playgirl",
        "pussy",
        "pussylips",
        "queef",
        "queer",
        "rape",
        "rape",
        "raper",
        "raping",
        "rapist",
        "rapist",
        "retard",
        "retarded",
        "rimjob",
        "sandnigger",
        "scat",
        "scrotum",
        "semen",
        "sex",
        "sexed",
        "sexed",
        "sexkitten",
        "sexslave",
        "sextoy",
        "sextoys",
        "sexy",
        "shat",
        "shit",
        "shit",
        "shitface",
        "shitfaced",
        "shitfuck",
        "shithead",
        "skank",
        "slave",
        "slavedriver",
        "slut",
        "sluts",
        "slutshame",
        "slutt",
        "smut",
        "submachine gun",
        "suckdick",
        "suckme",
        "suckoff",
        "suicide",
        "swastika",
        "tard",
        "terror",
        "terrorist",
        "testicle",
        "tits",
        "titties",
        "titty",
        "tittys",
        "torture",
        "tramp",
        "trannie",
        "trans",
        "tranny",
        "transexual",
        "transsexual",
        "transvestite",
        "trojan",
        "twat",
        "twink",
        "twinkie",
        "vibrator",
        "vibrater",
        "whore",
        "xxx"
    };
}